### ISSUE TITLE
project configuration?

### ISSUE THREAD

**Issue by ilg-ul** [flit/argon-rtos#1]
Hi Chris,

I tried to import your project in Eclipse and I'm afraid your project configuration is somehow damaged, the imported project has no settings, and the build is impossible.

I suggest you unpack a fresh Eclipse, install the GNU ARM Eclipse plug-ins and try the Import from Git.

You'll notice that in C/C++ Settings the project has no Tool Settings.

I did the test on two different platforms (OS X and GNU/Linux) with the same result.

Regards,

Liviu
GNU ARM Eclipse plug-ins maintainer

**Comment by flit** [comment]
Hi Liviu,

My apologies for the really slow response. 

I'm not sure why the project would be corrupt. My Eclipse install is a fresh install of the latest version plus GNU ARM Eclipse.

Anyway, I'll try to reproduce the issue (sounds like it should be easy) and fix it. 

Thanks for trying it out!

-c
