### ISSUE TITLE
`readyList` and `sleepingList`  initially unordered

### ISSUE THREAD

**Issue by diggit** [flit/argon-rtos#14]
All static ctors are called before `ar_kernel_run()` which configures list predicates. This results in `g_ar.readyList` and `g_ar.sleepingList` being possibly unordered at kernel startup. This causes that lower priority thread may run forever even though higher priority thread is waiting to be served.

**Comment by flit** [comment]
Good catch! Thanks 😄

**Comment by diggit** [comment]
IMO this is not 100% solution. There are no guarantees, that ctor of `ar_kernel_t` is called before any thread ctor.

**Comment by flit** [comment]
`g_ar` will be initialized by coping of `.rodata` to `.data` rather than by calling a ctor. `.data` init always happens before static initializer ctors are called.

**Comment by diggit** [comment]
Yeah, it is but also fragile to rely on compiler implicit behavior which depends on something what could easily change (ctor code).

Also in eb53912, you just _added and not moved_ initialization. Now, it is duplicated (here in ctor and in `ar_kernel_run`). Whenever you decide to change something in initializion, you'll have to change it on 2 places and well, that does not end well...

possible solutions:
- Initializing `g_ar` on demand from thread ctor unless already initialized. (quite ugly)
- sort all list at kernel startup
- create another list with objects _waiting to be registered_ kernel, which will then move them into correct list.

**Comment by flit** [comment]
> Yeah, it is but also fragile to rely on compiler implicit behavior which depends on something what could easily change (ctor code).
> (edit)In which case, `ar_kernel_t` could even erase list heads if called later than thread ctor.

The C++ standard makes this deterministic. I'm using the C++11 standard (I don't have a newer version handy).

Keep in mind that `ar_kernel_t` is a POD type and has no user-defined ctor.

§8.5.1 "Aggregates [dcl.init.aggr]" covers the type of initialization used with `g_ar`, namely using an initializer list and not calling a ctor.

§3.6.2 "Initialization of non-local variables [basic.start.init]" defines _constant initialization_, which includes "if an object with static or thread storage duration is not initialized by a constructor call and if every full-expression that appears in its initializer is a constant expression." 

Then the important bit: "Together, zero-initialization and constant initialization are called static initialization; all other initialization is dynamic initialization. Static initialization shall be performed before any dynamic initialization takes place."

The standard guarantees that initing `g_ar` using an initializer list will be completed prior to any dynamic initialization of global thread objects. This matches the actual implementations of toolchain startup code, with `.rodata` always copied to `.data` prior to calling static ctors. If you think about it, this must be the case, as a static ctor might depend on variables inited via constant initialization.

> Also in eb53912, you just added and not moved initialization. Now, it is duplicated (here in ctor and in `ar_kernel_run`). Whenever you decide to change something in initializion, you'll have to change it on 2 places and that does not end well...

The code in `ar_kernel_run()` to init the list predicates was removed. You're right that `g_ar` init is now split between 2 places. My intent was to move only the critical bit, the list predicates, to the initializer list. There is a comment in `ar_kernel_run()` that references this.

But it's probably a good idea to move all constant initialization of `g_ar` to the initializer list. And actually, the part of `ar_kernel_run()` that inits some of the `g_ar` members to false or 0 was already redundant, as `g_ar` was zero-initialized.

**Comment by diggit** [comment]
Thanks for detailed reply. I've discussed this issue with my colleague and result was identical. Sorry for being so negative without initial research.

I've seen you note about lack of designated initializers in in pre c++20 standards. `ar_kernel_t`  could benefit from c++ not needing designated initializers at all. (but that's different topic)
```cpp
struct ar_list_t { //could be simply List in Ar namespace...
    ar_list_node_t * m_head {nullptr};    //!< Pointer to the head of the list. Will be NULL if the list is empty.
    ar_sort_predicate_t m_predicate;    //!< Sort predicate to use for this list. Items are added to the end if NULL.
    ar_list_t(ar_sort_predicate_t predicate = nullptr) :
        m_predicate(predicate) {}
}

struct ar_kernel_t {
    ar_thread_t * currentThread {nullptr};    //!< The currently running thread.
    ar_list_t readyList {ar_thread_sort_by_priority};            //!< List of threads ready to run.
    ar_list_t suspendedList {};        //!< List of suspended threads.
    ar_list_t sleepingList {ar_thread_sort_by_wakeup};         //!< List of sleeping threads.
    //...
};
```
